#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM="xterm-256color"

# Handle Mac platforms for Homebrew
CPU=$(uname -p)
if [[ "$CPU" == "arm" ]]; then
  export HOMEBREW_ROOT=/opt/homebrew
  alias oldbrew=/usr/local/bin/brew
else
  export HOMEBREW_ROOT=/usr/local
fi

alias nano=${HOMEBREW_ROOT}/bin/nano

#zsh-completion installed by Intel Homebrew
fpath=(${HOMEBREW_ROOT}/share/zsh-completions $fpath)

#zsh-completion installed by ARM Homebrew
fpath=(${HOMEBREW_ROOT}/completions/zsh $fpath)

#User zsh-completion script
fpath=($HOME/.zsh_completions $fpath)

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# iterm shell integration
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/developer/google-cloud-sdk/path.zsh.inc" ]; then source "${HOME}/developer/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/developer/google-cloud-sdk/completion.zsh.inc" ]; then source "${HOME}/developer/google-cloud-sdk/completion.zsh.inc"; fi
export GOPATH=$HOME/developer/go
export PATH=$GOPATH/bin:$PATH

#ORACLE Client  
# CVV Mac
if [ -d "${HOME}/developer/oracle.instant.client" ] ; then
  export ORACLE_HOME=${HOME}/developer/oracle.instant.client
  export TNS_ADMIN=${ORACLE_HOME}/network/admin/
fi
#Titan Physics Servers
if [ -d "/usr/lib/oracle/19.3/client64" ] ; then 
  export ORACLE_HOME=/usr/lib/oracle/19.3/client64
  export TNS_ADMIN=${ORACLE_HOME}/lib/network/admin/
fi  

if [ -s ${ORACLE_HOME} ]; then
  export LD_LIBRARY_PATH=${ORACLE_HOME}:${LD_LIBRARY_PATH}
fi

#maven shit
export PATH=$PATH:${HOME}/developer/apache-maven-3.5.2/bin

#some useful scripts
export PATH=$PATH:${HOME}/developer/linux-scripts

#jmeter 
export PATH=$PATH:/Applications/apache-jmeter-4.0/bin/

# coreutils with standard names (not starting by 'g')
export PATH=${HOMEBREW_ROOT}/opt/coreutils/libexec/gnubin:$PATH

#titan_cli
export PATH=$PATH:${HOME}/developer/BBVA/connectors/titan/sqlcli/go/cli/build/bin/

alias tc=titan_cli_Darwin
compdef titan_cli_Darwin=titan_cli


#Set Java default version
if [ -f '/usr/libexec/java_home' ]; then export JAVA_HOME=$(/usr/libexec/java_home -v 17); fi

# add this configuration to ${HOME}/.zshrc
export HISTFILE=${HOME}/.zsh_history  # ensure history file visibility
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    no_share_history
unsetopt  share_history
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

export HH_CONFIG=hicolor        # get more colors

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
alias ls="ls --color=always"

# Ether Console stuff
export PATH=$PATH:$HOME/ecs-cli/
export ECS_CLI_KEY=$HOME/.ssh/e019682-live_key.pem
export ECS_CLI_CERT=$HOME/.ssh/e019682-live_cert.pem

#drivers DB2
if [ -f '/Applications/dsdriver/db2profile' ]; then source '/Applications/dsdriver/db2profile'; fi
export DB2HOME=/Applications/dsdriver
export IBM_DB_HOME=$DB2HOME
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib 
export DYLD_LIBRARY_PATH=$DB2HOME/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$DB2HOME/lib:$LD_LIBRARY_PATH

#para que go mod no vaya por el proxy de Google
export GOPRIVATE='*.bbva.com,*.igrupobbva'

#Android Tools
export PATH=$HOME/developer/android/:$PATH

#Openshift CLI
export PATH=$HOME/openshift_cli:$PATH
# Workaround for autocompletion  https://access.redhat.com/solutions/6896731

# HSTR configuration - add this to ${HOME}/.zshrc
alias hh=hstr                    # hh to be alias for hstr
setopt histignorespace           # skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor       # get more colors
if [[ $TERM_PROGRAM != "WarpTerminal" ]]; then
  bindkey -s "\C-r" "\C-a hstr -- \C-j"     # bind hstr to Ctrl-r (for Vi mode check doc
fi

#Physics mounts
export PATH=$HOME/developer/mounts/:$PATH
compdef mountf=ping
compdef sshp=ping

#TITAN Environment
export TITAN_DATASRV=localhost.titan.work.es.nextgen.igrupobbva:50050
export TITAN_DATASRV=localhost.titan.work.es.nextgen.igrupobbva:50050
#export TITAN_DATASRV=octa-sql.titan.work.es.nextgen.igrupobbva:50050
export TITAN_INSTANCE=db2-octa
export TITAN_DB=XTRE
export TITAN_CAFILE=/Users/carlosvigo/developer/BBVA/connectors/certs/global_root_issuinginfra_ca_work.pem
export TITAN_CERT=/Users/carlosvigo/developer/BBVA/connectors/certs/titan_client_infra_cert.pem
export TITAN_KEY=/Users/carlosvigo/developer/BBVA/connectors/certs/titan_client_infra_handled.key.pem
export TITAN_FILE=/Users/carlosvigo/developer/BBVA/connectors/db2_stressTest/queries/select_eñes.sql
export TITAN_IMPERSONATE_USER=XTRE
export TITAN_IMPERSONATE_HEADER=x-titan-security-runas-user
export TITAN_LOG_DIR=/Users/carlosvigo/developer/BBVA/connectors/db2_stressTest/logs
export TITAN_WRITEJSONRESULTS=false
export TITAN_WRITESEMAASRESULTS=false
export TITAN_NS=ether.titan.sql
export TITAN_MRID=work_titan_server
export TITAN_TLS=mutual
export TITAN_ISOLATION=readwrite
export TITAN_INTERVAL=1s
export TITAN_TIMEOUT=20m
export TITAN_WORKERS=200
export TITAN_REUSECONNECTIONS=false
export TITAN_IT=1
export TITAN_DURATION=5m
export TITAN_LB=round_robin_affinity
export TITAN_DNS=default
export TITAN_TXNSIZE=1
export TITAN_LOGLEVEL=error
export TITAN_NOPROGRESSBAR=false
export TITAN_VERBOSE=false
export TITAN_SENDHEADER='x-rho-tracecontext:{\"caller_runtime\":\"lra\",\"caller_id\":\"thecaller_id\",\"caller_id2\":\"thecaller_id2\",\"aap\":\"theaap\"}'



# Shell completion stuff
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$(brew --prefix)/share/zsh/site-functions:$FPATH
fi
autoload -Uz compinit
compinit -i

# export HTTPS_PROXY=zsgwtc1.igrupobbva:80
# export HTTP_PROXY=zsgwtc1.igrupobbva:80
# export http_proxy=zsgwtc1.igrupobbva:80
# export https_proxy=zsgwtc1.igrupobbva:80
export NO_PROXY=*.igrupobbva

alias pip=/opt/homebrew/bin/pip3
alias python=/opt/homebrew/bin/python3

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# Created by `pipx` on 2024-11-06 11:24:41
export PATH="$PATH:/Users/carlosvigo/.local/bin"
