#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM="xterm-256color"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/carlosvigo/developer/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/carlosvigo/developer/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/carlosvigo/developer/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/carlosvigo/developer/google-cloud-sdk/completion.zsh.inc'; fi
export GOPATH=$HOME/developer/go
export PATH=$GOPATH/bin:$PATH

#oracle client  
export PATH=~/oracle_instant_client_12_2:$PATH
export LD_LIBRARY_PATH=~/oracle_instant_client_12_2

#maven shit
export PATH=$PATH:~/developer/apache-maven-3.5.2/bin

#some useful scripts
export PATH=$PATH:~/developer/linux-scripts

#jmeter 
export PATH=$PATH:/Applications/apache-jmeter-4.0/bin/

# coreutils with standard names (not starting by 'g')
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH

#titan_cli
export PATH=$PATH:~/developer/BBVA/connectors/titan_cli/bin

#zsh-completion installed by Homebrew
fpath=(/usr/local/share/zsh-completions $fpath)

#Titan CLI autocomplete
source ~/.titan_cli/_titan_cli
alias tc=titan_cli

#Set Java default version
export JAVA_HOME='/usr/libexec/java_home -v 1.8'


# add this configuration to ~/.zshrc
export HISTFILE=~/.zsh_history  # ensure history file visibility
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    no_share_history
unsetopt  share_history
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

export HH_CONFIG=hicolor        # get more colors
bindkey -s "\C-r" "\eqhh\n"     # bind hh to Ctrl-r (for Vi mode check doc)

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
alias ls="ls --color=always"

# Ether Console stuff
export ECS_CLI_KEY=/Users/carlosvigo/.ssh/etherId.carlos.vigo_key.pem
export ECS_CLI_CERT=/Users/carlosvigo/.ssh/etherId.carlos.vigo_cert.pem

#drivers DB2
if [ -f '/Applications/dsdriver/db2profile' ]; then source '/Applications/dsdriver/db2profile'; fi
export DB2HOME=/Applications/dsdriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib 
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DB2HOME/dsdriver/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DB2HOME/dsdriver/lib

#para que go mod no vaya por el proxy de Google
export GOPRIVATE='*.bbva.com,*.igrupobbva'

#Android Tools
export PATH=$HOME/developer/android/:$PATH
