#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export TERM="xterm-256color"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"


# The next line updates PATH for the Google Cloud SDK.
if [ -f "${HOME}/developer/google-cloud-sdk/path.zsh.inc" ]; then source "${HOME}/developer/google-cloud-sdk/path.zsh.inc"; fi

# The next line enables shell command completion for gcloud.
if [ -f "${HOME}/developer/google-cloud-sdk/completion.zsh.inc" ]; then source "${HOME}/developer/google-cloud-sdk/completion.zsh.inc"; fi
export GOPATH=$HOME/developer/go
export PATH=$GOPATH/bin:$PATH

#oracle client  
export PATH=~/developer/oracle_instant_client_12_2:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/developer/oracle.instant.client
export ORACLE_HOME=~/developer/oracle.instant.client
export TNS_ADMIN=$ORACLE_HOME/network/admin/


#maven shit
export PATH=$PATH:~/developer/apache-maven-3.5.2/bin

#some useful scripts
export PATH=$PATH:~/developer/linux-scripts

#jmeter 
export PATH=$PATH:/Applications/apache-jmeter-4.0/bin/

# coreutils with standard names (not starting by 'g')
export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH

#titan_cli
export PATH=$PATH:~/developer/BBVA/connectors/titan_cli/bin

#zsh-completion installed by Homebrew
fpath=(/usr/local/share/zsh-completions $fpath)

#User zsh-completion script
fpath=($HOME/.zsh_completions $fpath)

#Titan CLI autocomplete
if [ -f "$HOME/.titan_cli/_titan_cli" ]; then source "$HOME/.titan_cli/_titan_cli"; fi

#DB2 Tester autocomplete
if [ -f "$HOME/.zsh_completions/_dbconntest" ]; then
  source "$HOME/.zsh_completions/_dbconntest"; 
  compdef _dbconntest dbconntest;
fi


alias tc=titan_cli

#Set Java default version
export JAVA_HOME='/usr/libexec/java_home -v 1.8'


# add this configuration to ~/.zshrc
export HISTFILE=~/.zsh_history  # ensure history file visibility
setopt    appendhistory     #Append history to the history file (no overwriting)
setopt    no_share_history
unsetopt  share_history
setopt    incappendhistory  #Immediately append to the history file, not just when a term is killed

export HH_CONFIG=hicolor        # get more colors

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
alias ls="ls --color=always"

# Ether Console stuff
export PATH=$PATH:$HOME/ecs-cli/
export ECS_CLI_KEY=$HOME/.ssh/e019682-live_key.pem 
export ECS_CLI_CERT=$HOME/.ssh/e019682-live_cert.pem

#drivers DB2
if [ -f '/Applications/dsdriver/db2profile' ]; then source '/Applications/dsdriver/db2profile'; fi
export DB2HOME=/Applications/dsdriver
export CGO_CFLAGS=-I$DB2HOME/include
export CGO_LDFLAGS=-L$DB2HOME/lib 
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DB2HOME/dsdriver/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DB2HOME/dsdriver/lib

#para que go mod no vaya por el proxy de Google
export GOPRIVATE='*.bbva.com,*.igrupobbva'

#Android Tools
export PATH=$HOME/developer/android/:$PATH

# HSTR configuration - add this to ~/.zshrc
alias hh=hstr                    # hh to be alias for hstr
setopt histignorespace           # skip cmds w/ leading space from history
export HSTR_CONFIG=hicolor       # get more colors
bindkey -s "\C-r" "\C-a hstr -- \C-j"     # bind hstr to Ctrl-r (for Vi mode check doc)

#TITAN Environment
export TITAN_DATASRV=localhost.titan.work.es.nextgen.igrupobbva:50050
#export TITAN_DATASRV=octa-sql.titan.work.es.nextgen.igrupobbva:50050
export TITAN_INSTANCE=db2-octa
export TITAN_DB=XTRE
export TITAN_CAFILE=/Users/carlosvigo/developer/BBVA/connectors/certs/global_root_issuinginfra_ca_work.pem
export TITAN_CERT=/Users/carlosvigo/developer/BBVA/connectors/certs/titan_client_infra_cert.pem
export TITAN_KEY=/Users/carlosvigo/developer/BBVA/connectors/certs/titan_client_infra_handled.key.pem
export TITAN_FILE=/Users/carlosvigo/developer/BBVA/connectors/db2_stressTest/queries/select_eñes.sql
export TITAN_IMPERSONATE_USER=XTRE
export TITAN_IMPERSONATE_HEADER=x-titan-security-runas-user
export TITAN_LOG_DIR=/Users/carlosvigo/developer/BBVA/connectors/db2_stressTest/logs
export TITAN_WRITEJSONRESULTS=false
export TITAN_WRITESEMAASRESULTS=false
export TITAN_NS=ether.titan.sql
export TITAN_MRID=work_titan_server
export TITAN_TLS=mutual
export TITAN_ISOLATION=readwrite
export TITAN_INTERVAL=1s
export TITAN_TIMEOUT=20m
export TITAN_WORKERS=200
export TITAN_REUSECONNECTIONS=false
export TITAN_IT=1
export TITAN_DURATION=5m
export TITAN_LB=round_robin_affinity
export TITAN_DNS=default
export TITAN_TXNSIZE=1
export TITAN_LOGLEVEL=error
export TITAN_NOPROGRESSBAR=false
export TITAN_VERBOSE=false